version: '3'

services:
  db:
    image: postgres:12
    volumes:
      - ./db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    env_file: ./db/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s

  code:
    build: .
    volumes:
      - .:/api
    ports:
      - "9080:9080"/home/zmiy
    depends_on:
      - db
    command: python3 api/api.py
